// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"time"
)

type MessageBlob struct {
	ID              int32
	Index           []byte
	Message         []byte
	SubmitTime      time.Time
	NeedsSubmission bool
}

type MessageBlobSubmission struct {
	ID      int32
	Index   []byte
	Message []byte
	Pubkey  []byte
}

type MessagePubkey struct {
	Pubkey     []byte
	SubmitTime time.Time
}
