// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"time"
)

type MessageMessage struct {
	ID         string
	Prefix     *string
	Message    *string
	SubmitTime *time.Time
}

type MessagePubkey struct {
	Pubkey     string
	SubmitTime *time.Time
}
